apiVersion: v1
kind: Secret
metadata:
  name: {{ include "caliber.fullname" . }}
  labels:
    {{- include "caliber.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.caliber.jwtSecret }}
  jwt-secret: {{ .Values.caliber.jwtSecret | b64enc | quote }}
  {{- else }}
  jwt-secret: {{ randAlphaNum 32 | b64enc | quote }}
  {{- end }}
  {{- if .Values.caliber.apiKeys }}
  api-keys: {{ .Values.caliber.apiKeys | b64enc | quote }}
  {{- end }}
---
{{- if and (not .Values.postgresql.enabled) (not .Values.externalDatabase.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "caliber.fullname" . }}-db
  labels:
    {{- include "caliber.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ .Values.externalDatabase.password | b64enc | quote }}
{{- end }}
---
{{- if and (not .Values.redis.enabled) (not .Values.externalRedis.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "caliber.fullname" . }}-redis
  labels:
    {{- include "caliber.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ .Values.externalRedis.password | b64enc | quote }}
{{- end }}
