name: OSV-Scanner

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: "0 3 * * 1"
  workflow_dispatch:

permissions:
  contents: read
  actions: read
  security-events: write

jobs:
  osv-scanner-pr:
    if: github.event_name == 'pull_request'
    uses: google/osv-scanner-action/.github/workflows/osv-scanner-reusable-pr.yml@v2.3.0
    permissions:
      contents: read
      actions: read
      security-events: write
    with:
      scan-args: >-
        -r
        ./
        --ignore=RUSTSEC-2026-0002
        --ignore=RUSTSEC-2025-0141
        --ignore=RUSTSEC-2024-0436
        --ignore=RUSTSEC-2021-0127

  osv-scanner-main:
    if: github.event_name != 'pull_request'
    uses: google/osv-scanner-action/.github/workflows/osv-scanner-reusable.yml@v2.3.0
    permissions:
      contents: read
      actions: read
      security-events: write
    with:
      scan-args: >-
        -r
        ./
        --ignore=RUSTSEC-2026-0002
        --ignore=RUSTSEC-2025-0141
        --ignore=RUSTSEC-2024-0436
        --ignore=RUSTSEC-2021-0127
